### ISSUE TITLE
Migration entre jsonV5 et v6 ?

### ISSUE THREAD

**Issue by Jaxom99** [laboiteproject/laboite-maker#1]
Bonjour,
Déjà merci pour tous vos efforts de documentation, c'est une super boite :smile_cat: J'aimerais la proposer pour un projet citoyen (il m'en faudrait alors 150, sur le pays de Redon ^^).

Mais j'ai un souci en essayant de refaire marcher le projet : si j'utilise arduinojson en v5 (.13.5) comme indiqué dans le Readme, j'ai l'erreur :
`StaticJsonDocument is a class from ArduinoJson 6 but version 5 is installed. Visit arduinojson.org to get more information.`
dans la fonction `boolean Boite::updateTile(unsigned int id)`

Et si je mets à jour en V6.19.4, j'ai l'erreur :
`'class ArduinoJson6194_F1::StaticJsonDocument<1024>' has no member named 'parseObject'`
dans la fonction `boolean Boite::getTiles()`, qui semble indiquer que le code n'a pas été (entièrement ?) migré en V6 : https://arduinojson.org/v6/doc/upgrade/

J'en appelle donc à votre science des bibliothèques Arduino pour remettre ma boite dans le droit chemin :smile: Merci pour votre aide !

**Comment by bgaultier** [comment]
Hello Jaxom,
[laboite_libraries.zip](https://github.com/laboiteproject/laboite-maker/files/8452077/laboite_libraries.zip)

Merci pour votre message ! Je n'arrive malheureusement pas à reproduire votre message, je me permets donc de joindre une archive contenant l'ensemble des librairies que j'utilise pour compiler la version 0.4 de **laboîte ESP32 maker edition**.
<img width="920" alt="Capture d’écran 2022-04-08 à 15 14 39" src="https://user-images.githubusercontent.com/177940/162443710-2749bf61-1bb3-4ffa-9deb-183546e785d6.png">

Bon courage,

--Baptiste

**Comment by bgaultier** [comment]
Fermeture automatique...
